resource_registry:
    OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
    OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
    OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
    InternalApiNetCidr: 172.17.5.0/24
    StorageNetCidr: 172.17.7.0/24
    StorageMgmtNetCidr: 172.17.8.0/24
    TenantNetCidr: 172.17.6.0/24
    ExternalNetCidr: 10.9.88.0/24
    ControlPlaneSubnetCidr: '24'
    InternalApiAllocationPools: [{'start': '172.17.5.10', 'end': '172.17.5.200'}]
    StorageAllocationPools: [{'start': '172.17.7.10', 'end': '172.17.7.200'}]
    StorageMgmtAllocationPools: [{'start': '172.17.8.10', 'end': '172.17.8.200'}]
    TenantAllocationPools: [{'start': '172.17.6.10', 'end': '172.17.6.200'}]
    ExternalAllocationPools: [{'start': '10.9.88.100',             'end': '10.9.88.109'}]     
    ExternalInterfaceDefaultRoute: 10.9.88.254
    InternalApiNetworkVlanID: 201
    StorageNetworkVlanID: 203
    StorageMgmtNetworkVlanID: 204
    TenantNetworkVlanID: 202
    NeutronExternalNetworkBridge: "''"
    ControlPlaneDefaultRoute: 192.0.2.1
    EC2MetadataIp: 192.0.2.1
    ControlPlaneIp: 192.0.2.1
    DnsServers: ["10.11.5.19", "10.10.160.2", "10.5.30.160"]
    OvercloudControlFlavor: controller
    OvercloudComputeFlavor: compute
